### ISSUE TITLE
How to upload the .8xv file to my calculator?

### ISSUE THREAD

**Issue by E-Radjas** [YvanTT/arTIfiCE#14]
I couldn't find any other place to post this, but on the arTIfiCE I can only download it as a .8xv file, even though it says it's supported by TI 83 premium CE, which only runs .8xp files. I would like some help there as I am trying to install artifice on my TI-83 premium CE, OS version 5.6.1.

**Comment by adriweb** [comment]
The 83 Premium CE accepts 8xv files as well, it's a normal extension used by lots of the TI apps. You can use TI Connect CE to transfer them.

**Comment by E-Radjas** [comment]
I can't even load the 8xv file to the Ti Connect CE app to send it to the calculator, I have attached a screen capture of my problem.

https://github.com/YvanTT/arTIfiCE/assets/80163139/a07b5720-9d63-4f9f-8993-5b10b5c504c9

**Comment by E-Radjas** [comment]
Damn... thanks it works now. I guess it's never too late to learn something
