### ISSUE TITLE
It Just Never Stops Loading

### ISSUE THREAD

**Issue by SuperSurvivor** [YvanTT/arTIfiCE#4]
### Describe the bug clearly: what happens: crash? reset? freeze? ...
When I open arTIfiCE through Cabri Jr (version 5.0.0.0089), it hangs immediately and forever on the starting screen, loading forever (the buffering circle runs forever). 

### How to reproduce the bug
1. Turn on calculator for the first time. 
2. Load the artifice payload onto the calculator and run it. 
3. It hangs. 

### Calculator version
This is the most important part:
- **Which calculator model exactly:**
**TI-84 Plus CE Python Edition**
(it must be one of the following: TI-83 Premium CE, TI-83 Premium CE Edition Python, TI-84 Plus CE, TI-84 Plus CE-T, TI-84 Plus CE-T Python Edition)

- **Which Boot and OS versions is the calculator running:**
**Boot: 5.6.1.0006** ; **OS: 5.6.0.0012**
(To know: turn on your calc, go to the home screen (where you do calculations), then press <kbd>mode</kbd> then <kbd>alpha</kbd> then <kbd>ln</kbd>. Get the two version numbers (for instance 5.0.0.0089 and 5.6.0.0020), then press <kbd>on</kbd> to return to the home screen.)

- **Which hardware revision is your calculator:**
**L-0421S**
(On the back of the calculator, in the middle towards the top, there are some characters, that may looks like a serial number: if there are two parts (serial numbers on the left, and some characters on the right, type here those characters on the right which should look like `L-0620P`. Otherwise, type down the serial number, it can look like `B06402A57`)
_This information is useful to know what TI changed in the hardware over time (it indicates where and where the calculator was manufactured, and the hardware revision letter), and helps tracking down the issue._

- **Approximately when did you buy the calculator:**
**August 31, 2021**
(Optional, this also helps to know when some versions came out in order to track changes over time)

### Additional info / Screenshots / Video

https://drive.google.com/file/d/1so2fENSfxxCexccODRsz_B8fDzNmNUKI/view?usp=sharing

**Comment by tctree333** [comment]
arTIfiCE will display ASM programs that are already on your calculator, so you might want to try loading the programs you want to run (like [Cesium](https://github.com/mateoconlechuga/cesium)) before launching arTIfiCE.
