### ISSUE TITLE
Support for TI-84 Plus CE OS 5.8.0

### ISSUE THREAD

**Issue by aknight2015** [YvanTT/arTIfiCE#7]
Do you have plans to update to support OS 5.8.0 for Plus CE (Non-python editions)?

**Comment by ibndiaye** [comment]
What about the python editions? or will it work for both if only non-python editions have it?

**Comment by adriweb** [comment]
Looks like they haven't updated the page but yes it works fine on 5.8, python or not.

**Comment by ibndiaye** [comment]
Oh nice, they might also want to update artifice on the page as well since its v1.1

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mpi3d** [comment]
> Oh nice, they might also want to update artifice on the page as well since its v1.1

Indeed. It will be corrected by #8.

**Comment by mpi3d** [comment]
> Looks like they haven't updated the page but yes it works fine on 5.8, python or not.

Pull request: #9.

**Comment by aknight2015** [comment]
Are you sure? I tried it and nothing happened.

**Comment by ibndiaye** [comment]
I'll also make a pull request for os 5.8 on the TI 83 Premium CE Python edition as soon as I have the time

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by YvanTT** [comment]
Yes it works fine on 5.8 (in fact it does not depend on the OS version, just CabriJr)

**Comment by aknight2015** [comment]
It took me a bit to figure it out, but I got it working. Thank you for this project. I can now play Chess on my calculator again.
